from django.conf.urls import patterns, include, url
import ltfu.views as views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'ltfu'
urlpatterns = patterns('',
                       url(r'^' + app_name + '/?$',views.outreach_dashboard),
                       url(r'^' + app_name + '/outreach_dashboard/?$',views.outreach_dashboard),
                       url(r'^' + app_name + '/outreach_defaulter_cohorts/?$',views.outreach_clinic_dashboard),
                       url(r'^' + app_name + '/view_defaulter_cohort/?$',views.view_defaulter_cohort),
                       url(r'^' + app_name + '/view_patient/?$',views.view_patient),
                       url(r'^' + app_name + '/create_defaulter_cohort/?$',views.create_defaulter_cohort),
                       url(r'^' + app_name + '/update_defaulter_cohorts/?$',views.update_defaulter_cohorts),
                       url(r'^' + app_name + '/patient_search/?$',views.patient_search),
                       url(r'^' + app_name + '/ajax_update_phone_number/?$',views.ajax_update_phone_number),
                       url(r'^' + app_name + '/ajax_get_defaulter_cohort/?$',views.ajax_get_defaulter_cohort),
                       url(r'^' + app_name + '/index/?$',views.index),
                       url(r'^' + app_name + '/ltfu_ampath/?$',views.ltfu_ampath),
                       url(r'^' + app_name + '/ltfu_clinics/?$',views.ltfu_clinics),
                       url(r'^' + app_name + '/ltfu_clinic/?$',views.ltfu_clinic),
                       url(r'^' + app_name + '/ltfu_by_range/?$',views.ltfu_by_range),
                       url(r'^' + app_name + '/ltfu_get_defaulter_list/?$',views.ltfu_get_defaulter_list),
                       url(r'^' + app_name + '/view_indicators_by_clinic/?$',views.view_indicators_by_clinic),
                       url(r'^' + app_name + '/view_indicators_by_provider/?$',views.view_indicators_by_provider),
                       url(r'^' + app_name + '/view_outreach_worker_forms_done/?$',views.view_outreach_worker_forms_done),
                       url(r'^' + app_name + '/view_data_entry_forms_done/?$',views.view_data_entry_forms_done),
                       url(r'^' + app_name + '/view_reason_missed_appt/?$',views.view_reason_missed_appt),
                       url(r'^' + app_name + '/update_defaulter_cohorts/?$',views.update_defaulter_cohorts),
                       url(r'^' + app_name + '/manage_defaulter_cohorts/?$',views.manage_defaulter_cohorts),
                       url(r'^' + app_name + '/delete_defaulter_cohort/?$',views.delete_defaulter_cohort),
                       url(r'^' + app_name + '/outreach_form/?[?]?$',views.outreach_form),
                       url(r'^' + app_name + '/outreach_worker_defaulter_list/?$',views.outreach_worker_defaulter_list),
                       url(r'^' + app_name + '/outreach_worker/?$',views.outreach_worker),
                       url(r'^' + app_name + '/retrospective_data_entry/?$',views.retrospective_data_entry),
                       url(r'^' + app_name + '/download_ltfu_list/?$',views.download_ltfu_list),
                       url(r'^' + app_name + '/view_data_entry_stats/?$',views.view_data_entry_stats),
                       url(r'^' + app_name + '/test/?$',views.test),
                       url(r'^' + app_name + '/ajax_patient_search/?$',views.ajax_patient_search),
                       url(r'^' + app_name + '/ajax_encounter_search/?$',views.ajax_encounter_search),
                       url(r'^' + app_name + '/ajax_concept_search/?$',views.ajax_concept_search),
                       url(r'^' + app_name + '/build_schema/?$',views.build_schema),
                       )
